# brew leaves -r
---
- name: Install brew apps (common)
  community.general.homebrew:
    name: "{{ item }}"
  with_items:
    # keep-sorted start
    - ack
    - ansible
    - atool
    - bash
    - bash-completion@2
    - coreutils
    - direnv
    - eza
    - fd
    - fpp
    - fzf
    - gh
    - git
    - gnu-sed
    - graphviz
    - htop
    - hugo
    - imagemagick
    - jq
    - less
    - lesspipe
    - make
    - mas
    - moreutils
    - mr
    - mtr
    - ncdu
    - pre-commit
    - ranger
    - shellcheck
    - stow
    - tig
    - tmux
    - tree
    - vim
    - watch
    - wget
    - zoxide
    - zsh
    - zsh-completions
    # keep-sorted end
- name: Install brew apps (cozy)
  tags:
    - cozy
  community.general.homebrew:
    name: "{{ item }}"
  with_items:
    # keep-sorted start
    - terraform
    # keep-sorted end
- name: Install brew apps (corp)
  tags:
    - corp
  community.general.homebrew:
    name: "{{ item }}"
  with_items:
    # keep-sorted start
    - minikube
    - warrensbox/tap/tfswitch
    # keep-sorted end
