#+TITLE: thiagowfx's emacs configuration

* Package Management
** straight.el
=straight.el= is a package manager for emacs:

Upstream URL: https://github.com/raxod502/straight.el

Bootstrap =straight.el=:

#+BEGIN_SRC emacs-lisp
(let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el"))
      (bootstrap-version 2))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+END_SRC

** use-package
=use-package= helps getting and configuring emacs packages:

Upstream URL: https://github.com/jwiegley/use-package

Activate =straight.el='s =use-package= integration:

#+BEGIN_SRC emacs-lisp
(straight-use-package 'use-package)
(setq use-package-always-ensure t)
#+END_SRC
* Extensions
  CLOSED: [2017-10-28 Sat 02:44]
** ace-jump-mode
=ace-jump-mode= allows the user to jump anywhere. =C-.= is the key, literally:

#+BEGIN_SRC emacs-lisp
(use-package ace-jump-mode
  :ensure t
  :bind (("C-." . ace-jump-mode)
         ("C-c C-." . ace-jump-word-mode)
         ("C-c M-g" . ace-jump-line-mode)))
#+END_SRC
** all-the-icons-dired
   CLOSED: [2017-10-26 Thu 02:52]
=all-the-icons-dired= displays icons next to each file in =dired=:

#+BEGIN_SRC emacs-lisp
(use-package all-the-icons-dired
  :ensure t
  :config (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+END_SRC
** better-defaults
=better-defaults= provides better defaults to emacs:

#+BEGIN_SRC emacs-lisp
(use-package better-defaults
  :ensure t)
#+END_SRC
** bookmark
=bookmark= allows the user to quickly jump to bookmarks:

- =C-x r l= to list bookmarks
- =C-x r m= to set a bookmark

#+BEGIN_SRC emacs-lisp
(use-package bookmark
  :ensure t)
#+END_SRC
** cmake-mode
=cmake-mode= is a mode to work with =*.cmake= files:

#+BEGIN_SRC emacs-lisp
(use-package cmake-mode
  :ensure t
  :defer-install t
  :mode "\\.cmake\\'")
#+END_SRC
** company-mode
   CLOSED: [2017-10-28 Sat 02:44]
=company=, "complete anything", is a text completion framework for emacs:

#+BEGIN_SRC emacs-lisp
(use-package company
  :ensure t
  :diminish company-mode
  :config (global-company-mode t))
#+END_SRC
** compile
=compile= enhances compilation features in emacs:

#+BEGIN_SRC emacs-lisp
(use-package compile
  :ensure t
  :config
  (setq compilation-always-kill t)
  (setq compilation-auto-jump-to-first-error t))
#+END_SRC
** dockerfile-mode
=dockerfile-mode= is a mode to edit a =Dockerfile=:

#+BEGIN_SRC 
(use-package dockerfile-mode
  :ensure t
  :defer-install t
  :mode "Dockerfile.*\\'")
#+END_SRC
** dracula-theme
=dracula-theme= is a dark theme for emacs:

#+BEGIN_SRC emacs-lisp
(use-package dracula-theme
  :ensure t
  :config (load-theme 'dracula t))
#+END_SRC
** evil
   CLOSED: [2017-10-28 Sat 02:44]
*** evil-mode
=evil-mode= is an extensible vi layer for emacs:

#+BEGIN_SRC emacs-lisp
(use-package evil
  :ensure t
  :config
  (evil-mode t)
  (setq evil-default-state 'emacs)

  ;; https://stackoverflow.com/a/16226006/1745064
  (define-key evil-normal-state-map "\C-e" 'evil-end-of-line)
  (define-key evil-insert-state-map "\C-e" 'end-of-line)
  (define-key evil-visual-state-map "\C-e" 'evil-end-of-line)
  (define-key evil-motion-state-map "\C-e" 'evil-end-of-line)
  (define-key evil-normal-state-map "\C-f" 'evil-forward-char)
  (define-key evil-insert-state-map "\C-f" 'evil-forward-char)
  (define-key evil-insert-state-map "\C-f" 'evil-forward-char)
  (define-key evil-normal-state-map "\C-b" 'evil-backward-char)
  (define-key evil-insert-state-map "\C-b" 'evil-backward-char)
  (define-key evil-visual-state-map "\C-b" 'evil-backward-char)
  (define-key evil-normal-state-map "\C-d" 'evil-delete-char)
  (define-key evil-insert-state-map "\C-d" 'evil-delete-char)
  (define-key evil-visual-state-map "\C-d" 'evil-delete-char)
  (define-key evil-normal-state-map "\C-n" 'evil-next-line)
  (define-key evil-insert-state-map "\C-n" 'evil-next-line)
  (define-key evil-visual-state-map "\C-n" 'evil-next-line)
  (define-key evil-normal-state-map "\C-p" 'evil-previous-line)
  (define-key evil-insert-state-map "\C-p" 'evil-previous-line)
  (define-key evil-visual-state-map "\C-p" 'evil-previous-line)
  (define-key evil-normal-state-map "\C-w" 'evil-delete)
  (define-key evil-insert-state-map "\C-w" 'evil-delete)
  (define-key evil-visual-state-map "\C-w" 'evil-delete)
  (define-key evil-normal-state-map "\C-y" 'yank)
  (define-key evil-insert-state-map "\C-y" 'yank)
  (define-key evil-visual-state-map "\C-y" 'yank)
  (define-key evil-normal-state-map "\C-k" 'kill-line)
  (define-key evil-insert-state-map "\C-k" 'kill-line)
  (define-key evil-visual-state-map "\C-k" 'kill-line))
#+END_SRC
*** evil-matchit
    CLOSED: [2017-10-27 Fri 02:33]
=evil-matchit= is the port of =vim-matchit= to emacs. Press =%= to activate it:

#+BEGIN_SRC emacs-lisp
(use-package evil-matchit
  :ensure t
  :config (global-evil-matchit-mode 1))
#+END_SRC
*** evil-exchange
=evil-exchange= is the port of =vim-exchange= to emacs. It allows the user to easily exchange text around:

#+BEGIN_SRC emacs-lisp
(use-package evil-exchange
  :ensure t
  :config (evil-exchange-cx-install))
#+END_SRC
*** evil-goggles
=evil-goggles= displays a visual hint when editing with =evil=:

#+BEGIN_SRC emacs-lisp
(use-package evil-goggles
  :ensure t
  :diminish evil-goggles-mode
  :config
  (evil-goggles-mode)

  ;; optionally use diff-mode's faces; as a result, deleted text will
  ;; be highlighed with `diff-removed` face which is typically
  ;; some red color (as defined by the color theme)
  ;; other faces such as `diff-added` will be used for other actions
  (evil-goggles-use-diff-faces)

  ;; to pulse the visual hint, rather than just show and hide it (experimental):
  (setq evil-goggles-pulse t))
#+END_SRC
** exec-path-from-shell
=exec-path-from-shell= ensures that environment variables inside emacs look the same as in the user's shell:

#+BEGIN_SRC
(use-package exec-path-from-shell
  :ensure t
  :config (when (memq window-system '(mac ns x))
            (exec-path-from-shell-initialize)))
#+END_SRC
** expand-region
=expand-region= increases the selected region by semantic units:

#+BEGIN_SRC emacs-lisp
(use-package expand-region
  :ensure t
  :bind ("C-=" . er/expand-region))
#+END_SRC
** idle-highlight-mode
=idle-highlight-mode= sets an idle timer that highlights all occurences in the buffer of the word under the point:

#+BEGIN_SRC emacs-lisp
(use-package idle-highlight-mode
  :ensure t
  :config (add-hook 'prog-mode-hook (lambda () (idle-highlight-mode t))))
#+END_SRC
** ido
*** ido-mode
=ido-mode= enhances emacs completion in the minibuffer:

#+BEGIN_SRC emacs-lisp
(defun recentf-ido-find-file ()
  "Find a recent file using ido."
  (interactive)
  (let ((file (ido-completing-read "Choose recent file: " recentf-list nil t)))
    (when file
      (find-file file))))

(use-package ido
  :ensure t
  :bind ("C-x C-r" . recentf-ido-find-file)
  :config
  (ido-mode t)
  (ido-everywhere t)
  (setq ido-show-dot-for-dired t))
#+END_SRC
*** ido-vertical-mode
=ido-vertical-mode= makes =ido-mode= display vertically:

#+BEGIN_SRC emacs-lisp
(use-package ido-vertical-mode
  :ensure t
  :config
  (ido-vertical-mode t)
  (setq ido-vertical-define-keys 'C-n-C-p-up-down-left-right)
  (setq ido-vertical-show-count t)

  ;; make =ido-vertical-mode= prettier
  ;; https://github.com/creichert/ido-vertical-mode.el
  (setq ido-use-faces t)
  (set-face-attribute 'ido-vertical-first-match-face nil
                      :background nil
                      :foreground "orange")
  (set-face-attribute 'ido-vertical-only-match-face nil
                      :background nil
                      :foreground nil)
  (set-face-attribute 'ido-vertical-match-face nil
                      :foreground nil))
#+END_SRC
*** flx-ido
=flx-ido= provides fuzzy matching for emacs:

#+BEGIN_SRC emacs-lisp
(use-package flx-ido
  :ensure t
  :config
  (flx-ido-mode 1)
  (setq ido-enable-flex-matching t))
#+END_SRC
*** ido-ubiquitous-mode
=ido-ubiquitous-mode= enhances emacs completion everywhere:

#+BEGIN_SRC emacs-lisp
(use-package ido-completing-read+
  :ensure t
  :config (ido-ubiquitous-mode t))
#+END_SRC
*** icomplete-mode
 =icomplete-mode= comes to the rescue whenever =ido= cannot be used:

#+BEGIN_SRC emacs-lisp
(use-package icomplete
  :ensure t
  :config (icomplete-mode t))
#+END_SRC
** find-file-in-project
=find-file-in-project= allows the user to:

- Find file / directory
- Review Diff / Patch / Commit quickly everywhere

#+BEGIN_SRC emacs-lisp
(use-package find-file-in-project
  :ensure t
  :commands (find-file-in-project))
#+END_SRC
** flycheck
   CLOSED: [2017-10-28 Sat 02:44]
=flycheck= is a modern on-the-fly syntax checking extension:

#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :ensure t
  :config (add-hook 'after-init-hook #'global-flycheck-mode))
#+END_SRC
** git-gutter
=git-gutter= indicates VCS changes on the emacs gutter:

#+BEGIN_SRC emacs-lisp
(use-package git-gutter
  :ensure t
  :diminish git-gutter-mode
  :config (global-git-gutter-mode t))
#+END_SRC
** guide-key
=guide-key= displays the available key bindings automatically and dynamically:

#+BEGIN_SRC emacs-lisp
(use-package guide-key
  :ensure t
  :diminish guide-key-mode
  :config
  (setq guide-key/guide-key-sequence '("C-c" "C-x r" "C-x 4" "C-c p"))
  (setq guide-key/idle-delay 2.0)
  (guide-key-mode t))
#+END_SRC
** linum-mode
=linum-mode= enables line numbers globally:

#+BEGIN_SRC emacs-lisp
(use-package linum
  :ensure t
  :config (global-linum-mode t))
#+END_SRC
** magit
=magit= is an emacs interface to the git VCS:

#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :config (setq magit-completing-read-function 'magit-ido-completing-read)
  :bind ("C-c m" . magit-status))
#+END_SRC
** manage-minor-mode
   CLOSED: [2017-10-26 Thu 03:05]
=manage-minor-mode= helps keeping track of the available / enabled / disabled minor-modes on emacs:

#+BEGIN_SRC emacs-lisp
(use-package manage-minor-mode
  :ensure t
  :commands (manage-minor-mode))
#+END_SRC
** markdown-mode
=markdown-mode= is a mode to edit =*.markdown= files:

#+BEGIN_SRC emacs-lisp
(use-package markdown-mode
  :ensure t
  :defer-install t
  :mode ("\\.markdown\\'" "\\.md\\'"))
#+END_SRC
** multiple-cursors
=multiple-cursors= support for emacs:

#+BEGIN_SRC emacs-lisp
(use-package multiple-cursors
  :ensure t
  :bind (("C->" . mc/mark-next-like-this)
         ("C-<" . mc/mark-previous-like-this)
         ("C-c C-<" . mc/mark-all-like-this)
         ("C-S-<mouse-1>" . mc/add-cursor-on-click)))
#+END_SRC
** org-mode
   CLOSED: [2017-11-27 Mon 01:28]
=org-mode= is for keeping notes, maintaining TODO lists, planning projects, and authoring documents with a fast and effective plain-text system:

#+BEGIN_SRC emacs-lisp
(use-package org
  :bind ("C-c a" . org-agenda)
  :config
  (setq org-todo-keywords '((sequence "TODO(t)" "STARTED(s)" "|" "DONE(d)")))
  (setq org-enforce-todo-dependencies t)
  (setq org-log-done t)

  ;; customize org todo faces
  (setq org-todo-keyword-faces (quote
    (("TODO" . "orange")
    ("STARTED" . "yellow")
    ("DONE" . "green"))))

  ;; enable compatibility with =windmove=:
  ;; http://orgmode.org/manual/Conflicts.html
  (add-hook 'org-shiftup-final-hook 'windmove-up)
  (add-hook 'org-shiftleft-final-hook 'windmove-left)
  (add-hook 'org-shiftdown-final-hook 'windmove-down)
  (add-hook 'org-shiftright-final-hook 'windmove-right))
#+END_SRC
** persistent-scratch
=persistent-scratch= makes emacs preserve the state of scratch buffers across sessions:

#+BEGIN_SRC emacs-lisp
(use-package persistent-scratch
  :if window-system
  :ensure t
  :config
  (persistent-scratch-setup-default))
#+END_SRC
** pkgbuild-mode
=pkgbuild-mode= is a mode to edit a =PKGBUILD= for Arch Linux:

#+BEGIN_SRC emacs-lisp
  (use-package pkgbuild-mode
    :ensure t
    :defer-install t
    :mode "PKGBUILD")
#+END_SRC
** projectile
=projectile= is a simple project management extension:

#+BEGIN_SRC emacs-lisp
(use-package projectile
  :ensure t
  :config
  (projectile-global-mode t))
#+END_SRC
** rainbow-delimiters
=rainbow-delimiters= is a "rainbow parentheses"-like mode which highlights delimiters such as parentheses, brackets or braces according to their depth:

#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
  :ensure t
  :config
  (add-hook 'clojure-mode-hook #'rainbow-delimiters-mode) 
  (add-hook 'emacs-lisp-mode-hook #'rainbow-delimiters-mode)
  (add-hook 'eval-expression-minibuffer-setup-hook #'rainbow-delimiters-mode)
  (add-hook 'hy-mode-hook #'rainbow-delimiters-mode)
  (add-hook 'ielm-mode-hook #'rainbow-delimiters-mode)
  (add-hook 'lisp-interaction-mode-hook #'rainbow-delimiters-mode)
  (add-hook 'lisp-mode-hook #'rainbow-delimiters-mode)
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
  (add-hook 'scheme-mode-hook #'rainbow-delimiters-mode))
#+END_SRC

** recentf
=recentf= keeps track of recently opened files:

#+BEGIN_SRC emacs-lisp
(use-package recentf
  :ensure t
  :config
  (recentf-mode t)
  (setq recentf-max-saved-items 100))
#+END_SRC
** savehist
=savehist= saves minibuffer histories between sessions:

#+BEGIN_SRC emacs-lisp
(use-package savehist
  :ensure t
  :config
  (savehist-mode t)
  (setq history-delete-duplicates t)

  ;; save additional variables
  (setq savehist-additional-variables '(kill-ring search-ring regexp-search-ring)))
#+END_SRC
** saveplace
=saveplace='s purpose is to make the point go to the last place where it was at the last time a file was opened:

#+BEGIN_SRC emacs-lisp
(use-package saveplace
  :ensure t
  :config
  (if (version<= emacs-version "24.5")
    (setq-default save-place t)
    (save-place-mode t)))
#+END_SRC
** smartparens
=smartparens= is a minor mode for dealing with pairs in emacs:

#+BEGIN_SRC emacs-lisp
(use-package smartparens
  :ensure t
  :config (smartparens-global-mode t)
  :diminish smartparens-mode)
#+END_SRC
** smex
=smex= is a smart replacement for =M-x=:

#+BEGIN_SRC emacs-lisp
(use-package smex
  :ensure t
  :config (smex-initialize)
  :bind (("M-x" . smex)
         ("M-X" . smex-major-mode-commands)
         ("C-c M-x" . execute-extended-command)))
#+END_SRC
** undo-tree
=undo-tree= improves the emacs undo system:

- =C-_= for =undo-tree-undo=
- =M-_= for =undo-tree-redo=

#+BEGIN_SRC emacs-lisp
(use-package undo-tree
  :ensure t
  :diminish undo-tree-mode
  :config
  (setq undo-tree-auto-save-history t)
  (setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undo")))
  (global-undo-tree-mode t)
  :bind ("C-+" . undo-tree-redo))
#+END_SRC

** web-mode
=web-mode= is an autonomous emacs major-mode for editing web templates:

#+BEGIN_SRC emacs-lisp
(use-package web-mode
  :ensure t
  :config
  (add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))

 ;; enable web-mode for plain HTML files
 (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode)))
#+END_SRC
** windmove
=windmove= lets the user move easily through windows:

- =S-Left=
- =S-Right=
- =S-Up=
- =S-Down=

#+BEGIN_SRC emacs-lisp
(use-package windmove
  :ensure t
  :config
  (setq windmove-wrap-around t)
  (windmove-default-keybindings))
#+END_SRC
** winner-mode
=winner-mode= lets the user move easily through window layouts:

- =C-c left=
- =C-c right=

#+BEGIN_SRC emacs-lisp
(use-package winner
  :ensure t
  :config (winner-mode t))
#+END_SRC
** ws-butler-mode
   CLOSED: [2017-10-26 Thu 02:45]
=ws-butler-mode= is an unobtrusive way to trim spaces from end of line:

#+BEGIN_SRC emacs-lisp
(use-package ws-butler 
  :ensure t
  :config (ws-butler-global-mode t)
  :diminish ws-butler-mode)
#+END_SRC
** yaml-mode
=yaml-mode= is a mode to work with =*.yaml= files:

#+BEGIN_SRC emacs-lisp
(use-package yaml-mode
  :ensure t
  :defer-install t
  :mode ("\\.yaml\\'" "\\.yml\\'"))
#+END_SRC
** yasnippets
   CLOSED: [2017-10-28 Sat 02:44]
=yasnippet= is a template system for emacs; expansions and snippets:

#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :ensure t
  :config
  (yas-reload-all)
  (add-hook 'prog-mode-hook #'yas-minor-mode))
#+END_SRC
* Customizations
** backups
Inhibit all backup files.

#+BEGIN_SRC emacs-lisp
(setq backup-inhibited t)
(setq make-backup-files nil)
(setq delete-old-versions t)
(setq auto-save-default nil)
(setq create-lockfiles nil)
#+END_SRC
** comint
=comint= is a package that defines a general command-interpreter-in-a-buffer:

#+BEGIN_SRC emacs-lisp
(bind-keys :map comint-mode-map
           ("<up>" . comint-previous-input)
           ("<down>" . comint-next-input))
#+END_SRC
** uniquify
=uniquify= overrides Emacs’ default mechanism for making buffer names unique:

#+BEGIN_SRC emacs-lisp
(require 'uniquify)
(setq uniquify-separator "/")
#+END_SRC
** GUI
Disable fancy GUI stuff:

#+BEGIN_SRC emacs-lisp
(when (window-system)
  (tooltip-mode t)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (blink-cursor-mode -1)
  (global-hl-line-mode t)

  (progn
    (global-visual-line-mode t)
    (diminish 'visual-line-mode))

  ;; enable the menu bar in MacOS GUI
  (if (and (eq system-type 'darwin) window-system)
    (menu-bar-mode 1)
    (menu-bar-mode -1))

  (setq-default indicate-empty-lines t))
#+END_SRC
** initialization messages
Suppress all initialization messages:

#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
(setq initial-scratch-message nil)
#+END_SRC
** miscellaneous tweaks
A bag for all non-categorized tweaks:

#+BEGIN_SRC emacs-lisp
(delete-selection-mode t)
(setq visible-bell t)
(setq-default fill-column 80)
(prefer-coding-system 'utf-8)
(when (display-graphic-p)
  (setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING)))
(put 'narrow-to-region 'disabled nil)
(put 'upcase-region 'disabled nil)
(put 'downcase-region 'disabled nil)
(require 'iso-transl)
(setq save-interprogram-paste-before-kill t)
(setq select-enable-primary t)
(setq vc-follow-symlinks t)
#+END_SRC
** minibuffer
Provide better defaults for the minibuffer:

#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
(setq resize-mini-windows t)
(setq echo-keystrokes 0.1)
#+END_SRC
** modeline
Improve modeline information:

#+BEGIN_SRC emacs-lisp
(column-number-mode t)
(which-function-mode t)
#+END_SRC
** user-defined functions
#+BEGIN_SRC emacs-lisp
(defun cleanup-whitespace ()
  "Cleanup the buffer whitespace"
  (interactive)
  (save-excursion
    (message "Cleaning whitespace...")
    (whitespace-cleanup)
    (delete-trailing-whitespace)
    (message "Cleaning whitespace...DONE")))

(defun settings ()
  "Edit the genesis.org file"
  (interactive)
  (find-file "~/.emacs.d/genesis.org"))

(defun unfill-paragraph ()
  "Take a multi-line paragraph and makes it into a single line of text."
  ;; Taken from: http://github.com/howardabrams/dot-files.git
  (interactive)
  (let ((fill-column (point-max)))
    (fill-paragraph nil)))
#+END_SRC
** user-defined information
Hi there!

#+BEGIN_SRC emacs-lisp
(setq user-full-name "Thiago Perrotta")
(setq user-mail-address "tbperrotta@gmail.com")
#+END_SRC
** user-defined keybindings
Add personal keybindings:

#+BEGIN_SRC emacs-lisp
(bind-key "C-;" 'comment-dwim)
(bind-key "RET" 'newline-and-indent)
#+END_SRC
