---
- name: disable double space auto-period on macOS
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: do not show recent applications in Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
    state: present

# https://docs.ansible.com/ansible/latest/collections/community/general/osx_defaults_module.html
- name: enable software auto update
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: int
    value: 1

# https://stackoverflow.com/questions/98310/focus-follows-mouse-plus-auto-raise-on-mac-os-x
- name: set focus follows mouse on Terminal.app
  community.general.osx_defaults:
    domain: com.apple.Terminal
    key: FocusFollowsMouse
    type: bool
    value: true
    state: present

# https://stackoverflow.com/questions/39972335/how-do-i-press-and-hold-a-key-and-have-it-repeat-in-vscode
- name: unset key press and hold on VSCode.app
  community.general.osx_defaults:
    domain: com.microsoft.VSCode
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present

- name: set fn key to show emoji & symbols
  community.general.osx_defaults:
    domain: com.apple.HIToolbox
    key: AppleFnUsageType
    type: int
    value: 2
    state: present
