#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Windows 8 x86_64 UEFI-GPT" {
	insmod part_gpt
	insmod fat
	insmod search_fs_uuid
	insmod chain
	search --fs-uuid --set=root --hint-bios=hd1,gpt2 --hint-efi=hd1,gpt2 --hint-baremetal=ahci1,gpt2 E662-93C5
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}

 menuentry "Windows 8 64-bit Custom" {
	set root='(hd1,gpt2)'
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}

menuentry "Windows 8 aaaaaaaaaa" {
	insmod part_gpt
	insmod fat
	insmod search_fs_uuid
	insmod chain
	search --fs-uuid --hint-bios=hd1,gpt2 --hint-efi=hd1,gpt2 --hint-baremetal=ahci1,gpt2 E662-93C5
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}

menuentry "My Windows 8 OS" {
	search --fs-uuid --no-floppy --set=root E662-93C5
	chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}
