#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "My Windows 8 OS" {
    search --fs-uuid --no-floppy --set=root E662-93C5
    chainloader (${root})/EFI/Microsoft/Boot/bkpbootmgfw.efi
}
