# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/refs/heads/dev/schemas/match.schema.json
# https://espanso.org/docs/
matches:
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
