# yaml-language-server: $schema=../../../../../vendor/schemas/espanso-match.schema.json
# https://espanso.org/docs/
matches:
  # keep-sorted start newline_separated=yes
  # Unicode Character “⠀” (U+2800) Braille Pattern Blank
  - trigger: ":  "
    replace: "⠀"

  - trigger: ":email"
    replace: "thiago@perrotta.dev"

  - trigger: ":github"
    replace: "https://github.com/thiagowfx"

  - trigger: ":left"
    replace: "←"

  - trigger: ":linkedin"
    replace: "https://www.linkedin.com/in/thiagoperrotta"

  - trigger: ":lorem"
    replace: |-
      Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
      eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
      voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet
      clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
      amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
      nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
      sed diam voluptua. At vero eos et accusam et justo duo dolores et ea
      rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
      dolor sit amet.

  - trigger: ":option"
    replace: "⌥"

  # macOS: Option + 3
  - trigger: ":pound"
    replace: "£"

  - trigger: ":right"
    replace: "→"

  - trigger: ":star"
    replace: "★"

  - trigger: ":therefore"
    replace: "∴"

  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - triggers:
      - ":cqd"
      - ":qed"
    replace: "∎"

  - triggers:
      - ":hugo:link"
      - ":hugo:ref"
    replace: '{{< ref "$|$" >}}'

  - triggers:
      - ":hugo:prev"
      - ":hugo:previously"
    replace: '[Previously]({{< ref "$|$" >}}).'
# keep-sorted end
