#!/bin/sh
# Display the last 5 commit messages when committing.

readonly COMMITS=5

readonly COMMIT_FILE="$1"
readonly SOURCE="$2"
readonly HASH="$3"

case "$SOURCE" in
    merge|squash|message)
        ;;
    ""|commit|template)
        if [ -z "$HASH" ]; then
            echo "# Last $COMMITS commits:" >> "$COMMIT_FILE"
            git log --pretty="#   %h %s [%an]" -$COMMITS >> "$COMMIT_FILE"
        fi
        ;;
    *)
        echo "Unexpected type '$SOURCE' in prepare-commit-msg hook" >&2
        exit 1
esac
