# brew list --cask -1
---
- name: Install brew casks (common)
  community.general.homebrew_cask:
    name: "{{ item }}"
  with_items:
    # keep-sorted start
    - 1password
    - anki
    - calibre
    - duckduckgo
    - font-hermit
    - font-ibm-plex-mono
    - google-chrome
    - google-drive
    - hiddenbar
    - karabiner-elements
    - logseq
    - maccy
    - qlmarkdown
    - raycast
    - rectangle
    - spotify
    - telegram
    - visual-studio-code
    - vlc
    - whatsapp
    # keep-sorted end
- name: Install brew casks (cozy)
  tags:
    - cozy
  community.general.homebrew_cask:
    name: "{{ item }}"
  with_items:
    # keep-sorted start
    - basictex
    - element
    - jellyfin
    - qbittorrent
    - tailscale
    - windscribe
    # keep-sorted end
- name: Install brew casks (corp)
  tags:
    - corp
  community.general.homebrew_cask:
    name: "{{ item }}"
  with_items:
    # keep-sorted start
    - slack
    # keep-sorted end
