#!/bin/bash
# bootstrap/update dotfiles

PUBLIC_REPOS=(
	"dotfiles"
	"scripts"
	"snippets"
	"vim"
)

for repo in "${PUBLIC_REPOS[@]}"; do
	repodir="$HOME/.$repo"
	if [[ ! -d "$repodir" ]]; then
		(cd "$HOME" && git clone --recursive --depth=1 "https://github.com/thiagowfx/$repo" "$repodir")
	else
		(cd "$repodir" && git pull --recurse-submodules && git push origin master)
	fi
done

# vim-plug
if [[ -d "$HOME/.vim/vim-plug" ]]; then
	vim +PlugInstall +PlugClean! +qall
fi

# stow dotfiles
hash stow &>/dev/null && stow --dir="$HOME/.dotfiles" bash git screen tmux

# pdotfiles
if [[ -d $HOME/.pdotfiles ]]; then
	(cd "$HOME/.pdotfiles" && git commit -a -m "t-emerge-dotfiles automatic update")
	(cd "$HOME/.pdotfiles" && git pull --recurse-submodules && git push origin master)
	hash stow &>/dev/null && stow --dir="$HOME/.pdotfiles" gnupg macos ssh
fi
