" no vi
set nocompatible

" pathogen (this line should come first)
execute pathogen#infect()

"
""" plugin settings
let g:airline_powerline_fonts=0
let g:airline_theme='powerlineish'
let g:airline#extensions#tabline#enabled = 1

let g:syntastic_cpp_compiler_options='-std=c++11'
""" plugin settings end
"

" enable syntax highlighting
filetype plugin indent on
syntax on

" set the leader key
let mapleader=","

" set colorscheme
set t_Co=256
colorscheme jellybeans

" enable colorcolumn
set colorcolumn=80
highlight ColorColumn ctermbg=yellow

" display tabs, trailing spaces and EOLs
set list
set listchars=tab:\ ¬,trail:.,eol:↵ 

" set user mappings with the leader key
map <Leader>m :make<cr>
map <Leader>s :sort<cr>

"
""" set user mappings without the leader key
" enter in normal mode
inoremap jj <ESC>
""" set user mappings without the leader key end
"

"
""" user settings
" set sensible defaults for wildmenu
set wildmenu wildmode=list:full wildignore=*.swp,*.bak,*.bkp

" enable undo history
set history=10000
set undodir=$HOME/.cache/vim/vimrc_undodir
set undofile undolevels=10000 undoreload=10000

" good indentation control
set autoindent smartindent smarttab

" always use utf-8
set encoding=utf-8 fileencodings=utf-8 termencoding=utf-8

" set sensible defaults for searching
set incsearch hlsearch wrapscan
set ignorecase

" improve usability
set showmatch visualbell
set autoread
set infercase smartcase
set shortmess=atI
set laststatus=2
set ttyfast
set cursorline
set number ruler
set showcmd
set showmode
set ttimeout ttimeoutlen=100
set foldmethod=indent
set nofoldenable

" disable backups
set noswapfile nobackup nowb

" set sensible defaults for completion
set completeopt=menuone,longest

" scroll automatically whenever needed
set scrolloff=5 sidescrolloff=5
""" user settings end
"

" religious stuff
" set shiftround shiftwidth=4 tabstop=4 softtabstop=4
" set expandtab
