#!/usr/bin/env bash
# perform a full system upgrade

set -euo pipefail

log() {
	local bold=$(tput bold) normal=$(tput sgr0)
	echo "${bold}$*${normal}"
}

run_if_exists() {
	if command -v "$1" >/dev/null 2>&1; then
		if [[ $# -eq 1 ]]; then
			log "Running $1..."
			"$1"
		else
			shift
			log "Running $*..."
			"$@"
		fi
	elif [[ -d "$1" ]]; then
		shift
		log "Running $*..."
		"$@"
	fi
}

case "$(uname)" in
	# linux
	Linux)
		# alpine linux
		run_if_exists "apk" doas apk upgrade

		# arch linux
		run_if_exists "pacman" sudo pacman -Syu

		# debian linux
		# warning: macos has /usr/bin/apt which is a Java thing
		run_if_exists "apt-get" sudo apt-get upgrade
		run_if_exists "apt-get" sudo apt-get autoremove

		# linux @ corp
		run_if_exists "glinux-updater"
		;;

	# macOS
	Darwin)
		# macos mas: Mac App Store
		run_if_exists "mas" mas upgrade

		# macos homebrew
		run_if_exists "brew" brew upgrade
		run_if_exists "brew" brew cleanup

		# macos @ corp
		run_if_exists "mule" sudo mule upgrade
		run_if_exists "gmac-updater"

		# macos system upgrade
		run_if_exists "softwareupdate" softwareupdate --install --all
		;;
esac

# nix
run_if_exists "nix-channel" nix-channel --update
run_if_exists "nix-env" nix-env -u

# pihole
run_if_exists "pihole" pihole -up
run_if_exists "pihole" pihole -g

# dotfiles
run_if_exists "$HOME/.dotfiles" git -C "$HOME/.dotfiles" pull origin master

# dotfiles @ corp
run_if_exists "$HOME/.dotfiles_corp" git -C "$HOME/.dotfiles_corp" pull origin master
