#!/usr/bin/env bash
# perform a full system upgrade

set -euo pipefail

log() {
	local bold=$(tput bold) normal=$(tput sgr0)
	echo "${bold}$*${normal}"
}

run_if_exists() {
	if command -v "$1" >/dev/null 2>&1; then
		if [[ $# -eq 1 ]]; then
			log "Running $1..."
			"$1"
		else
			shift
			log "Running $*..."
			"$@"
		fi
	elif [[ -d "$1" ]]; then
		shift
		log "Running $*..."
		"$@"
	fi
}

# usage: do_git <path/to/git/repo>
do_git() {
	if [[ -d "$1" ]]; then
		run_if_exists "$1" git -C "$1" pull origin master
	fi
}

case "$(uname)" in
	# linux
	Linux)
		# alpine linux
		run_if_exists "apk" doas apk upgrade

		# arch linux
		run_if_exists "pacman" sudo pacman -Syu

		# debian linux
		# warning: macos has /usr/bin/apt which is a Java thing
		run_if_exists "apt-get" sudo apt-get upgrade -y
		run_if_exists "apt-get" sudo apt-get autoremove
		;;

	# macOS
	Darwin)
		# homebrew
		run_if_exists "brew" brew upgrade
		run_if_exists "brew" brew cleanup

		# system update and app store
		# run_if_exists "softwareupdate" softwareupdate --install --all
		run_if_exists "mas" mas upgrade
		;;

	# windows
	MINGW*)
		# third-party package manager
		run_if_exists "scoop" scoop update
		;;
esac

# flatpaks
run_if_exists "flatpak" flatpak update

# nix
run_if_exists "nix-channel" nix-channel --update
run_if_exists "nix-env" nix-env -u

# pihole
# update pihole itself and gravity lists
run_if_exists "pihole" pihole -up

# dotfiles
do_git "$HOME/.dotfiles"
do_git "$HOME/.dotfiles_corp"
