#!/bin/bash
#
# Housekeeping for a macOS system.
#

# Exit immediately upon receiving C-c.
trap ctrl_c INT
function ctrl_c	(){
	exit 1
}

# Ask for sudo password upfront.
sudo -v

if [[ "$(uname)" == "Darwin" ]]; then
	sudo softwareupdate -i -a

	# homebrew
	if command -v brew &>/dev/null; then
		brew update
		brew upgrade
		brew cleanup
		brew prune
		brew doctor

		# casks upgrade
		brew cu

		# homebrew backup
		brew bundle dump --force --global

	fi

	# macports
	if command -v port &>/dev/null; then
		sudo port selfupdate
		sudo port upgrade outdated
		sudo port uninstall leaves
	fi
fi

# vim: ft=sh
